/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.livreController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MHD
 */
public class livreView extends javax.swing.JFrame {


    livreController controller = new livreController();
    String titre ;
    String nomAuteur;
    int nbCopie;
    String datePublication;
    String isbn;
    int idCat; 
    DefaultComboBoxModel cmbModel;
    /**
     * Creates new form livreView
     */
    public livreView()  {
        initComponents();
        initTable();
        initComboModel();

        
    }
    public void initTable(){
     
         try{
          ResultSet rs = controller.getDao().getRsAll();
          controller.getModel().setResultSet(rs);

        }catch(SQLException e){
              JOptionPane.showMessageDialog(rootPane, e);
        }

       tblDisplay.setModel(controller.getModel());
    }

    public void initComboModel(){
       cmbModel = new DefaultComboBoxModel();

      try{
            controller.getModel().setResultSet(controller.getDao().getRsAll());
            for(int i=0;i<controller.getModel().getColumnCount() ; i++){

                   if(controller.getModel().getColumnName(i).equals("idCat")){
                       cmbModel.addElement("categorie");
                  }else{
                   cmbModel.addElement(controller.getModel().getColumnName(i));    
                  }
                    
            } 
   
            comboSearch.setModel(cmbModel);
            
      }catch(SQLException e){

          JOptionPane.showMessageDialog(rootPane, e);
      }
         
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idLivreTxt = new javax.swing.JTextField();
        titreTxt = new javax.swing.JTextField();
        auteurTxt = new javax.swing.JTextField();
        nbCopieTxt = new javax.swing.JTextField();
        datePublicationTxt = new javax.swing.JTextField();
        isbnTxt = new javax.swing.JTextField();
        categorieCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        ajouterBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        sauvegarderBtn = new javax.swing.JButton();
        supprimerBtn = new javax.swing.JButton();
        chercherBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        comboSearch = new javax.swing.JComboBox<>();
        chercherTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion Livres Regulier");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Id Livre :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Titre :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Auteur");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("nombre Copie :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Date publication :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ISBN :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Categorie :");

        idLivreTxt.setEnabled(false);

        categorieCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Math", "Music", "Physique", " " }));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ajouterBtn.setText("Ajouter");
        ajouterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.setEnabled(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        sauvegarderBtn.setText("Sauvegarder");
        sauvegarderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderBtnActionPerformed(evt);
            }
        });

        supprimerBtn.setText("Supprimer");
        supprimerBtn.setEnabled(false);
        supprimerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBtnActionPerformed(evt);
            }
        });

        chercherBtn.setText("Chercher");
        chercherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(ajouterBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sauvegarderBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chercherBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supprimerBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterBtn)
                    .addComponent(sauvegarderBtn)
                    .addComponent(chercherBtn)
                    .addComponent(updateBtn)
                    .addComponent(supprimerBtn))
                .addContainerGap())
        );

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titre", "Auteur", "nbCopie", "datePublication", "ISBN", "Categorie"
            }
        ));
        tblDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblDisplayMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplay);

        jLabel9.setText("Chercher par :");

        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titre", "Auteur", " " }));

        chercherTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chercherTxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idLivreTxt)
                            .addComponent(titreTxt)
                            .addComponent(auteurTxt)
                            .addComponent(nbCopieTxt)
                            .addComponent(datePublicationTxt)
                            .addComponent(categorieCombo, 0, 304, Short.MAX_VALUE)
                            .addComponent(isbnTxt))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chercherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idLivreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chercherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(auteurTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nbCopieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(datePublicationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(isbnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(categorieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String livreId = idLivreTxt.getText();
        String titre = titreTxt.getText();
        String nomAuteur = auteurTxt.getText();
        String nbCopie = nbCopieTxt.getText();
        String datePublication = datePublicationTxt.getText();
        String isbn = isbnTxt.getText();
        controller.getLivre().setIdLivre(Integer.parseInt(livreId));
        controller.getLivre().setTitre(titre);
        controller.getLivre().setNomAuteur(nomAuteur);
        controller.getLivre().setNbCopie(Integer.parseInt(nbCopie));
        controller.getLivre().setDatePublication(datePublication);
        controller.getLivre().setIsbn(isbn);

        try{
                controller.getDao().update(controller.getLivre());
                JOptionPane.showMessageDialog(rootPane, "livre updated succesfully");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, e);
        }
        initTable();

    }//GEN-LAST:event_updateBtnActionPerformed

    private void supprimerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerBtnActionPerformed

    private void ajouterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtnActionPerformed
        
        idLivreTxt.setText("");
        titreTxt.setText("");
        auteurTxt.setText("");
        nbCopieTxt.setText("");
        datePublicationTxt.setText("");
        isbnTxt.setText("");
       
        sauvegarderBtn.setEnabled(true);
        ajouterBtn.setEnabled(false);
           
    }//GEN-LAST:event_ajouterBtnActionPerformed

    private void sauvegarderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderBtnActionPerformed

        if(getRecordValidation() == true ){
             
              titre  = titreTxt.getText().trim();
             nomAuteur = auteurTxt.getText().trim();
             nbCopie  = Integer.parseInt(nbCopieTxt.getText().trim());
             datePublication =  datePublicationTxt.getText().trim();
             isbn = isbnTxt.getText().trim();
             idCat = categorieCombo.getSelectedIndex() + 1;


             controller.getLivre().setTitre(titre);
             controller.getLivre().setNomAuteur(nomAuteur);
             controller.getLivre().setNbCopie(nbCopie);
             controller.getLivre().setDatePublication(datePublication); 
             controller.getLivre().setIsbn(isbn); 
             controller.getLivre().setIdCat(idCat); 

             try{
                controller.getDao().insert(controller.getLivre());
                JOptionPane.showMessageDialog(rootPane, "livre saved succefully");
                ajouterBtn.setEnabled(true);
                sauvegarderBtn.setEnabled(false);
                initTable();
             }catch(SQLException e){
                 e.printStackTrace();
             }



         }
    }//GEN-LAST:event_sauvegarderBtnActionPerformed

    private void chercherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherBtnActionPerformed
        
    }//GEN-LAST:event_chercherBtnActionPerformed

    private void chercherTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chercherTxtKeyReleased
        
        String colName = comboSearch.getSelectedItem().toString();
        String word = chercherTxt.getText();
        try{
               ResultSet rs = controller.getDao().search(colName, word);
               controller.getModel().setResultSet(rs); 

             

        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
            tblDisplay.setModel(controller.getModel());
}

    }//GEN-LAST:event_chercherTxtKeyReleased

    private void tblDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayMouseClicked
             
    }//GEN-LAST:event_tblDisplayMouseClicked

    private void tblDisplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayMouseReleased
        
        int i = tblDisplay.getSelectedRow();
        idLivreTxt.setText(controller.getModel().getValueAt(i, 0).toString());
        titreTxt.setText(controller.getModel().getValueAt(i, 1).toString());
        auteurTxt.setText(controller.getModel().getValueAt(i, 2).toString());
        nbCopieTxt.setText(controller.getModel().getValueAt(i, 3).toString());
        datePublicationTxt.setText(controller.getModel().getValueAt(i, 4).toString());
        isbnTxt.setText(controller.getModel().getValueAt(i, 5).toString());

        ajouterBtn.setEnabled(true);
        updateBtn.setEnabled(true);
        supprimerBtn.setEnabled(true);
        sauvegarderBtn.setEnabled(true);

    }//GEN-LAST:event_tblDisplayMouseReleased
    public boolean getRecordValidation(){
          if(controller.getValidation().isEmpty(titreTxt.getText().trim())){
                JOptionPane.showMessageDialog(rootPane, "plz enter the titre");
                titreTxt.requestFocus();
                return false;
          }else if(controller.getValidation().isEmpty(auteurTxt.getText().trim())){
                JOptionPane.showMessageDialog(rootPane, "plz enter the autheur name ");
                auteurTxt.requestFocus();
                return false; 
          }else if(controller.getValidation().isEmpty(nbCopieTxt.getText().trim())){
                JOptionPane.showMessageDialog(rootPane, "plz enter the copies number ");
                nbCopieTxt.requestFocus();
                return false;
          }else if(controller.getValidation().isEmpty(datePublicationTxt.getText().trim())){
                JOptionPane.showMessageDialog(rootPane, "plz enter the publication date ");
                datePublicationTxt.requestFocus();
                return false;
          }else if(controller.getValidation().isEmpty(isbnTxt.getText().trim())){
                JOptionPane.showMessageDialog(rootPane, "plz enter the isbn  ");
                isbnTxt.requestFocus();
                return false;
          }else if(controller.getValidation().isEmpty( ((String) categorieCombo.getSelectedItem()))){
                JOptionPane.showMessageDialog(rootPane, "plz select a categorie  ");
                
                return false;
          }
               return true;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(livreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(livreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(livreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(livreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new livreView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterBtn;
    private javax.swing.JTextField auteurTxt;
    private javax.swing.JComboBox<String> categorieCombo;
    private javax.swing.JButton chercherBtn;
    private javax.swing.JTextField chercherTxt;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JTextField datePublicationTxt;
    private javax.swing.JTextField idLivreTxt;
    private javax.swing.JTextField isbnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nbCopieTxt;
    private javax.swing.JButton sauvegarderBtn;
    private javax.swing.JButton supprimerBtn;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTextField titreTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
